apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-2
spec:
  storageClassName: local-storage-sc # É o nome do SC que será usado. SC/PV/PVC não usam label
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
