apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  # Pode ser feito um arquivo com replicaSet, mas o deployment já faz o serviço e ainda cria o POD
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod
