apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: standard # É o nome do PV que será usado. PV/PVC não usam label
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
