apiVersion: v1
kind: PersistentVolume
metadata:
  name: sistema-noticias-pv
spec:
  storageClassName: sistema-noticias-sc # É o nome do PV que será usado. PV/PVC não usam label
  capacity:
    storage: 1Gi
  # volumeMode: Filesystem # Filesystem is default
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/lucasnoman/Documents/Dev/Codes/Alura/Kubernetes-2/volumes/storage-class
  persistentVolumeReclaimPolicy: Retain
